CONFIG = {
    'SLEEP_TIME': 30,
    'ENABLE_SLACK': True,
    'SUBNET_TO_SCAN': '10.0.0.0/24',
    'SLACK_API_TOKEN': 'xoxp-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    'SLACK_CHANNEL': '#honeypot'
}